const siteConfig = {
    title: "MetaDawgs - Complete Quests & Earn Crypto Rewards | Solana Gaming Platform",
    description:
        "Join MetaDawgs, the ultimate gamified crypto platform on Solana. Complete quests, earn MetaDawgs tokens, climb leaderboards, and connect with the strongest crypto community. Start your Web3 journey today!",
    author: "MetaDawgs Team",
    keywords: [
        // Primary keywords
        "MetaDawgs",
        "crypto quests",
        "earn crypto",
        "Solana gaming",
        "Web3 rewards",
        "blockchain gaming",
        "crypto community",
        "MetaDawgs token",
        // Secondary keywords
        "gamified DeFi",
        "SocialFi platform",
        "crypto leaderboard",
        "quest rewards",
        "Solana ecosystem",
        "play to earn",
        "crypto challenges",
        "Web3 social",
        // Long-tail keywords
        "how to earn crypto tokens",
        "best Solana gaming platform",
        "crypto quest platform",
        "Web3 community rewards",
        "Solana token rewards",
        "gamified crypto earning",
        "blockchain quest game",
        "crypto social platform",
        // Technical keywords
        "DeFi",
        "NFT",
        "cryptocurrency",
        "digital assets",
        "smart contracts",
        "decentralized",
        "tokenomics",
        "airdrop",
    ],
    themeColor: "#000000",
    favicon: "/assets/favicon.ico",
    robot: "/robots.txt",
    socialLinks: {
        twitter: "https://x.com/Meta_Dawgs",
        telegram: "https://t.me/Metadawgsportal",
        facebook: "",
        youtube: "https://www.youtube.com/@MetaDawgs",
        instagram: "",
        linkedin: "",
        discord: "",
        roadmap: "https://metadawg.gitbook.io/metadawgs/",
    },
    url: "https://metadawgs.com",
};

export default siteConfig;
